version: "3.9"

services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
    networks:
      - app_network
    depends_on:
      - backend

  backend:
    build: ./backend
    expose:
      - "5000"
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 1GB
    networks:
      - app_network

networks: 
  app_network: 
    driver: bridge
