terraform {
  required_providers {
    local = {
      source  = "hashicorp/local"
      version = "~> 2.5"
    }
  }
}

provider "local" {}

locals {
  files = [for i in range(1, var.numberFiles + 1) : {
    fileNumber = i
    fileName = "file${i}.txt"
  }]
}

resource "local_file" "files" {
  for_each = { for item in local.files : item.fileName => item }

  filename = "${var.envName}/${each.value.fileName}"
  content  = "This is file number ${each.value.fileNumber} for ${var.envName} env generated by terraform, The user inputed text is : ${var.inputText}"
}
