terraform {
  required_providers {
    local = {
      source  = "hashicorp/local"
      version = "~> 2.5"
    }
  }
}

provider "local" {}

locals {
  files = flatten([
    for env in var.envs : [
      for i in range(1, var.numberFiles + 1) : {
        env = env
        fileName = "file${i}.txt"
        fileNumber = i
      }
    ]
  ])
}

resource "local_file" "files" {
  for_each = {
    for item in local.files :
    "${item.env}-${item.fileName}" => item
  }

  filename = "${each.value.env}/${each.value.fileName}"
  content  = "This is file number ${each.value.fileNumber} for ${each.value.env} env generated by terraform, The user inputed text is : < DO NOT HARDCODE, this TEXT can be anything, different for each file and env>"
}
